---

# Whatever it takes to update Solr from 4.1 from 4.10.4, according to:
# https://github.com/freelawproject/courtlistener/issues/567
- hosts: solr
  tasks:
  - include_vars: ../defaults.yml

  # Set up new Solr with old cores and configs
  - name: copy old core configs to new Solr
    become: yes
    become_user: root
    command: cp -R "/usr/local/solr/example/solr/{{ item }}/" "/usr/local/solr-4.10.4/example/solr/{{ item }}"
    args:
      creates: "/usr/local/solr-4.10.4/example/solr/{{ item }}"
    with_items:
      - audio
      - collection1
      - person


  - name: set up new solr properties files
    become: yes
    become_user: root
    template:
      src="templates/{{ item }}.properties.j2"
      dest="/usr/local/solr-4.10.4/example/solr/{{ item }}/core.properties"
    with_items:
      - audio
      - collection1
      - person

  # Solr doesn't like to load things from outside of its instance directory. So,
  # in they go via symlinks.
  - name: tweak synonym, protwords, and stopwords files to be symlinks
    become: yes
    become_user: root
    file:
      src="{{ install_root }}/Solr/conf/lang/{{ item[1] }}.txt"
      path="/usr/local/solr-4.10.4/example/solr/{{ item[0] }}/conf/lang/{{ item[1] }}.txt"
      state=link
      force=yes
    with_nested:
      - ['audio', 'collection1', 'person']
      - ['synonyms_en', 'stopwords_en', 'protwords_en']

  # The example solr config crashes unless you stub out this file. See:
  # http://stackoverflow.com/a/10896359/64911
  - name: replace the default elevate file
    become: yes
    become_user: root
    template:
      src="templates/elevate.xml"
      dest="/usr/local/solr-4.10.4/example/solr/{{ item }}/conf/elevate.xml"
    with_items:
      - audio
      - collection1
      - person

  # Stop Solr, swap out the old, and swap in the new.
  - name: stop solr
    service:
      name=solr
      state=stopped
  - name: backup old solr
    become: yes
    become_user: root
    command: >
      mv /usr/local/solr /usr/local/solr-4.1
      creates=/usr/local/solr-4.1
      removes=/usr/local/solr
  - name: link up new solr
    become: yes
    become_user: root
    file:
      src=/usr/local/solr-4.10.4
      path=/usr/local/solr
      state=link
      force=yes

  # Start things up again.
  - name: restart solr
    become: yes
    become_user: root
    service:
      name=solr
      state=started

- hosts: celery
  tasks:
  - name: start celery
    become: yes
    become_user: root
    service:
      name=celeryd
      state=started

# Optimize a second time, with new configs and versions.
- hosts: solr
  tasks:
  - include_vars: ../defaults.yml
  - name: optimize all solr cores
    django_manage:
      app_path={{ install_root }}
      command="cl_update_index --optimize-everything"
      virtualenv={{ virtualenv_root }}
