---

# Create new solr core for RECAP.
- hosts: solr
  tasks:
  - include_vars: ../defaults.yml
  - name: copy collection1 directory to recap
    become: yes
    become_user: root
    command: cp -R "/usr/local/solr/example/solr/collection1/" "/usr/local/solr/example/solr/recap/"
    args:
      creates: "/usr/local/solr/example/solr/recap"
  - name: set up properties file
    become: yes
    become_user: root
    template:
      src="templates/recap.properties.j2"
      dest="/usr/local/solr/example/solr/recap/core.properties"
  - name: update symlinks
    become: yes
    become_user: root
    file:
      src="{{ install_root }}/Solr/conf/recap_schema.xml"
      dest="/usr/local/solr/example/solr/recap/conf/schema.xml"
      state=link
      force=yes
  - name: restart solr
    become: yes
    become_user: root
    service:
      name=solr
      state=restarted
