name: docker build and test

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out solr
        uses: actions/checkout@v2-beta
        with:
          repository: freelawproject/courtlistener-solr-server
          ref: master
          path: courtlistener-solr-server
      - name: Set up solr permissions
        working-directory: courtlistener-solr-server
        run: |
          # DON'T DO THIS IN PROD!
          sudo find data -type f -exec chmod 777 {} \;
          sudo find solr -type f -exec chmod 777 {} \;
      - name: Install dependencies
        run: sudo apt-get install jq
      - name: Start the latest image
        working-directory: courtlistener-solr-server
        run: docker run -d -p 8983:8983 --volume `pwd`/solr/cores:/etc/opt/solr:ro --volume `pwd`/data:/var/opt/solr/indices --name solr freelawproject/solr:0.5
      - name: List docker statuses
        run: docker ps -a
      - name: Check docker is running
        # jq will convert a true/false JSON value to an exit code
        run: docker inspect -f '{{.State.Running}}' solr | jq --exit-status '.'

