name: docker build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out solr
        uses: actions/checkout@v2-beta
        with:
          repository: freelawproject/courtlistener-solr-server
          ref: master
          path: courtlistener-solr-server
      - name: Set up solr permissions
        working-directory: courtlistener-solr-server
        run: |
          # DON'T DO THIS IN PROD!
          sudo find data -type f -exec chmod 777 {} \;
          sudo find solr -type f -exec chmod 777 {} \;
      - name: Install jq & curl
        run: sudo apt-get install jq curl
      - name: Start the latest image
        working-directory: courtlistener-solr-server
        run: docker run -d -p 8983:8983 --volume `pwd`/solr/cores:/etc/opt/solr:ro --volume `pwd`/data:/var/opt/solr/indices freelawproject/solr:latest
      - name: Test a simple query
        run: |
          curl 'http://localhost:8983/solr/collection1/select?q=*%3A*&wt=json&indent=true' > output.json
          jq output.json --exit-status '.response.numFound'
