name: docker build and test

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    services:
      solr:
        image: freelawproject/solr
        ports:
          - 8983:8983
        options: --volume ${{ github.workspace }}/solr/cores:/etc/opt/solr:ro --volume ${{ github.workspace }}/data:/var/opt/solr/indices --name solr
    steps:
      - name: Check out solr
        uses: actions/checkout@v2-beta
        with:
          repository: freelawproject/courtlistener-solr-server
          ref: master
          path: courtlistener-solr-server
      - name: ls
        run: ls -a ${{ github.workspace }}
      - name: Set up solr permissions
        working-directory: courtlistener-solr-server
        run: |
          # DON'T DO THIS IN PROD!
          sudo find data -type f -exec chmod 777 {} \;
          sudo find solr -type f -exec chmod 777 {} \;
      - name: List docker statuses
        run: docker ps -a
      - name: Restart solr to access repo files
        uses: docker://docker
        with:
          args: docker restart solr

      - name: Install jq & curl
        run: sudo apt-get install jq curl
      - name: List docker statuses
        run: docker ps -a
      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v1
      - name: Test a simple query
        run: |
          curl -v 'http://127.0.0.1:8983/solr/collection1/select?q=*%3A*&wt=json&indent=true'
          jq output.json --exit-status '.response.numFound'
